version: '3'
services:
  mongo:
    image: "mongo"
    container_name: "mongo-prs"
    ports:
      - "27017:27017"
  server:
    container_name: "prs-server"
    build: .
    depends_on:
      - mongo
    ports:
      - "8080:8080"
